### PR TITLE
Don't set `FFI_BUILDING` when including `ffi.h`.

### PR DESCRIPTION
**Pull request by dbrnz**
Otherwise we get link errors under Windows.

### CODE REVIEW

**Comment by bjia56** [comment]
Just tested this on my portable-python repo and unfortunately it breaks on Windows linking static libffi 3.4.2. Newer libffi might fix the issue since FFI_BUILDING seems to be removed upstream, however since I'm not able to easily switch libffi's for now, I'll add a workaround to the buildsystem to optionally re-enable the variable.

**Comment by dbrnz** [comment]
I'm using the prebuilt `libffi` from the CPython repo:

```
    if(WIN32)
        set(CPYTHON_BIN_DEPS cpython-bin-deps)
        set(WINDOWS_LIBFFI_ARCHIVE libffi-${WINDOWS_LIBFFI_VERSION})

        set(LIBFFI_LIBRARY_DIR ${PROJECT_BINARY_DIR}/${CPYTHON_BIN_DEPS}-${WINDOWS_LIBFFI_ARCHIVE}/amd64)

        if(NOT EXISTS ${LIBFFI_LIBRARY_DIR})

            message("Downloading '${WINDOWS_LIBFFI_ARCHIVE}'...")

            file(DOWNLOAD
                https://github.com/python/${CPYTHON_BIN_DEPS}/archive/${WINDOWS_LIBFFI_ARCHIVE}.zip
                ${PROJECT_BINARY_DIR}/zips/${WINDOWS_LIBFFI_ARCHIVE}.zip
                SHOW_PROGRESS)

            execute_process(COMMAND ${CMAKE_COMMAND} -E tar -xf zips/${WINDOWS_LIBFFI_ARCHIVE}.zip --format=zip
                            WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
                            OUTPUT_QUIET)
        endif()

        # Set LibFFI options for external CMake project build

        list(APPEND WINDOWS_LIBFFI_OPTIONS -DLibFFI_INCLUDE_DIR=${LIBFFI_LIBRARY_DIR}/include)
        list(APPEND WINDOWS_LIBFFI_OPTIONS -DLibFFI_LIBRARY=${LIBFFI_LIBRARY_DIR}/${LIBFFI_IMPORT_LIBRARY})
    endif()
```

**Comment by bjia56** [comment]
Oh interesting, didn't know that repo existed. I might pull the prebuilt binaries from there as well, thanks for sharing. I've been using this one, which hasn't been updated https://github.com/python-cmake-buildsystem/libffi

**Comment by dbrnz** [comment]
I spotted it by seeing how the official Python build now does things -- have a look at https://github.com/python/cpython/blob/main/PCbuild/get_externals.bat and the corresponding `get_external.py`.

**Comment by bjia56** [comment]
The CPython libffi binaries work with 3.11 and 3.12, but unfortunately don't work on 3.9 or 3.10 due to compilation errors:
```
2024-04-02T20:28:47.7058924Z D:\a\portable-python\portable-python\build\Python-3.9.19\Modules\_ctypes\cfield.c(1507,25): error C2099: initializer is not a constant [D:\a\portable-python\portable-python\build\python-build\CMakeBuild\extensions\extension_ctypes.vcxproj]
```

I suspect it may be related to this ctypes refactoring, which was not backported: https://github.com/python/cpython/commit/38f331d4656394ae0f425568e26790ace778e076

Will try re-enabling FFI_BUILDING for versions 3.10 and prior.

**Comment by dbrnz** [comment]
Presumably you've found the libFFI sources used by CPython [here](https://github.com/python/cpython-source-deps/tree/libffi)?

**Comment by bjia56** [comment]
I've been using the upstream libffi sources for non-Windows, but will check out the CPython version. Thanks!

**Comment by dbrnz** [comment]
> I've been using the upstream libffi sources for non-Windows.

I've found CMake happily finds the system libffi -- under Linux `apt install libffi-dev` (Debian/Ubuntu) or `dnf install libffi-devel` (RHEL); for macOS there's no need to install anything.

**Comment by bjia56** [comment]
Yep, system libffi usually does work. The portable builds I've been working on are cross compiled for several architectures and target glibc 2.17, so I've had to build pretty much every dependency from source.
